spring.application.name=Server
spring.datasource.url=jdbc:postgresql://localhost:5432/IQFarm_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

gemini.api.key=${GEMINI_API_KEY:}

# File Storage
app.file.storage-path=uploads/images/
app.file.storage-url=http://localhost:8080/uploads/images/
app.file.max-size=10485760

# Multipart
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
