#### VARIABLES
@HOST = http://localhost:
@PORT = 8080

@SERVER = {{HOST}}{{PORT}}

### Register a new user
POST {{SERVER}}/api/auth/register
Content-Type: application/json

{
  "name": "Tebza",
  "surname": "Smith",
  "email": "thulanismith@gmail.com",
  "password": "teboho@1234"
}

### Login with existing user
POST {{SERVER}}/api/auth/login
Content-Type: application/json

{
  "email": "thulanismith@gmail.com",
  "password": "teboho@1234"
}

### Login with incorrect password (to test error handling)
POST {{SERVER}}/api/auth/login
Content-Type: application/json

{
  "email": "thulaninyombolo@gmail.com",
  "password": "wrongpassword"
}