@HOST = http://localhost:
@PORT = 8080

@SERVER = {{HOST}}{{PORT}}

POST {{SERVER}}/api/farm
Content-Type: application/json

{
  "ownerId": "2",
  "farmName": "Good Farm too",
  "farmAddress": "44 Stanley Ave, Milpark, Johannesburg, 2092",
  "longitude": "",
  "latitude" : ""
}